export const REQUEST_PLAYLISTS = 'REQUEST_PLAYLISTS'
export const RECEIVE_PLAYLISTS = 'RECEIVE_PLAYLISTS'

export const REQUEST_PLAYLIST = 'REQUEST_PLAYLIST'
export const RECEIVE_PLAYLIST = 'RECEIVE_PLAYLIST'
export const CREATE_PLAYLIST = 'CREATE_PLAYLIST'
